backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

local_backend: true
# Uncomment below to enable drafts
# publish_mode: editorial_workflow


media_library:
  name: cloudinary
  output_filename_only: false
  multiple: true
  config:
    cloud_name: spauf8qy2fzk
    api_key: 847638784652599
    multiple: true
    default_transformations:
      - - fetch_format: auto
          width: 1280
          quality: auto
          crop: scale

media_folder: "static/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "reviews" # Used in routes, e.g., /admin/collections/blog
    label: "Reviews" # Used in the UI
    label_singular: "Review"
    folder: "reviews" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - label: 'Venue Image'
        name: 'venue_image'
        widget: 'image'
        required: false
        allow_multiple: false
        multiple: false
      - { label: "Date visited", name: "date", widget: "date", }
      - { label: 'Location', name: 'location', widget: 'string' }
      - { label: 'Google Map', name: 'google_map', widget: 'string', required: false }  
      - { label: "Tags", name: "tags", widget: "select", multiple: true , options: ["Food", "Drink", "Accommodation"] }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: 'Images'
        name: 'images'
        widget: 'image'
        required: false
        allow_multiple: true
        multiple: true
      
      - label: "Ratings"
        name: "ratings"
        widget: "list"
        types:
          - label: 'Atmosphere'
            name: 'atmosphere'
            widget: object
            fields:
            - { label: rating, name: rating, widget: number, value_type: float, min: 1, max: 10, step: 0.5, default: 10 }
          - label: 'Drinks'
            name: 'drinks'
            widget: object
            fields:
            - { label: rating, name: rating, widget: number, value_type: float, min: 1, max: 10, step: 0.5, default: 10 }
          - label: 'Food'
            name: 'food'
            widget: object
            fields:
            - { label: rating, name: rating, widget: number, value_type: float, min: 1, max: 10, step: 0.5, default: 10 }
          - label: 'Value for money'
            name: 'value_for_money'
            widget: object
            fields:
            - { label: rating, name: rating, widget: number, value_type: float, min: 1, max: 10, step: 0.5, default: 10 }




# =========================================================================================

  # Our pages e.g. About
  - name: "pages"
    label: "Page"
    folder: "pages"
    create: false # Change to true to allow editors to create new pages
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Permalink", name: "permalink", widget: "string" }
      - label: "Navigation" # https://www.11ty.dev/docs/plugins/navigation/
        name: "eleventyNavigation"
        widget: "object"
        fields:
          - { label: "Key", name: "key", widget: "string" }
          - { label: "Order", name: "order", widget: "number", default: 0 }
      - { label: "Body", name: "body", widget: "markdown" }
